{
 "title": "Throughput",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (messages/s)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(num_processed_messages[10s])"
    },
    {
     "expr": "rate(num_incoming_messages[10s])"
    },
    {
     "expr": "rate(num_outgoing_messages[10s])"
    }
   ]
  },
  {
   "title": "Spurious",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "p1a" },
    { "expr": "p1b_success" },
    { "expr": "p1b_preempted" },
    { "expr": "p2b_preempted" },
    { "expr": "leader_heartbeat_received" }
   ]
  },
  {
   "title": "Mock sent messages/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(num_sent_mock_messages[10s])"
    }
   ]
  },
  {
   "title": "Mock received messages/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(num_received_mock_messages[10s])"
    }
   ]
  }
 ]
}