name: Build Autoscaling Paxos
on:
  push:
    branches:    
      - '**' 
jobs:
    main:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master
        - name: Cache protobuf
          uses: actions/cache@v2
          id: cache-protobuf
          with:
            path: protobuf-3.13.0
            key: ${{ runner.os }}-protobuf
        - name: APT packages
          run: |
            sudo apt-get update
            sudo apt-get install -y unzip ca-certificates apt-transport-https libpq-dev libzmq3-dev build-essential
            sudo snap install cmake --classic
        - name: Build protobuf library
          if: steps.cache-protobuf.outputs.cache-hit != 'true'
          run: |
            sudo wget https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protobuf-all-3.13.0.zip
            sudo unzip protobuf-all-3.13.0.zip
            cd protobuf-3.13.0
            sudo ./configure CXX=g++ CXXFLAGS='-std=c++17 -O3 -g'
            sudo make -j2
        - name: Install protobuf
          run: |
            cd protobuf-3.13.0
            sudo make install
            sudo ldconfig
        - name: Building binaries w/ CMake
          run: |
            sudo cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ .
            sudo cmake --build . --target all -- -j 2
            sudo mkdir build
            find . -maxdepth 1 -type f  -executable | xargs -I {} sudo mv {} build
        - name: Pushing binaries to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: "build"
