name: Build Autoscaling Paxos
on:
  push:
    branches:    
      - '**' 
jobs:
    main:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master
        - name: Building binaries w/ CMake
          run: |
            sudo apt-get update
            mv scripts/compile_aspaxos.sh .
            sudo chmod +x ./compile_aspaxos.sh
            sudo ./compile_aspaxos.sh
        - name: Pushing binaries to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: "build"
