name: Build Autoscaling Paxos
on:
  push:
    branches:    
      - main
jobs:
    main:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master
        - name: Cache protobuf
          uses: actions/cache@v2
          id: cache-protobuf
          with:
            path: protobuf-3.13.0
            key: ${{ runner.os }}-protobuf
        - name: APT packages
          run: |
            sudo ./scripts/install_dependencies_for_building.sh
        - name: Build protobuf library
          if: steps.cache-protobuf.outputs.cache-hit != 'true'
          run: |
            sudo ./scripts/download_protobuf.sh
        - name: Install protobuf
          run: |
            sudo ./scripts/install_protobuf.sh
        - name: Building w/ CMake
          run: |
            sudo ./scripts/build.sh
        - name: Pushing Build Directory to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: build
